### ISSUE TITLE
При нажатии на круглую кнопку, появляется квадратная рамка

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.2#1]
Так и должно быть?)
![image](https://user-images.githubusercontent.com/26929933/36366260-e4a4a9a8-157f-11e8-8ea7-5dd7b2d73f01.png)

**Comment by chmnkh** [comment]
Ну это для пункта стандартов "!При установке элементу outline: none обязательно выставить стили для :focus этому элементу". Если смущает именно то, что квадратная, то тут явного правильного варианта не было, поэтому я сделал как-то, вроде не сильно ужасно)

**Comment by Zarwlar** [comment]
Прочти ещё раз это правило, и посмотри, как оно выполнено у тебя, плз)

**Comment by chmnkh** [comment]
Так норм?

**Comment by Zarwlar** [comment]
:+1:
