### ISSUE TITLE
В scripts package.json пакеты нужно юзать не глобальные, а локальные

### ISSUE THREAD

**Issue by kinda-neat** [AlexeyCheremnykh/task-2.2#10]

**Comment by kinda-neat** [comment]
Попробуй склонировать свой репозиторий и выполнить npm install, там проблемки возникают :)

**Comment by Zarwlar** [comment]
@AlexeyCheremnykh в этом проекте при использовании `npm i` возникает ошибка с _jquery-ui-slider-pips_. Из-за него не получается собраться проект

**Comment by chmnkh** [comment]
По поводу локальных и глобальных пакетов: там же просто в PATH препендится путь до файлов для запуска локальных модулей (на скрине PATH из вывода npm run env):
![image](https://user-images.githubusercontent.com/18498637/36933328-af7c3a78-1f09-11e8-8967-ba30f99700d0.png)
Т.е. хоть как в локальном каталоге искаться будет, а если уже там не найдет, то пойдет дальше по PATH'y. Так же и в доках писать советуют вроде:

![image](https://user-images.githubusercontent.com/18498637/36933360-12f59f18-1f0a-11e8-995a-d53977bea669.png)

Я, если честно, пока разбирался, забыл в чем там проблема была, когда мы это первый раз обсудили, но тут вроде ничего такого, он просто по PATH'у будет искать командные файлы, причем сначала в локальный node_modules лезть.

**Comment by chmnkh** [comment]
Исправил во всех проектах

**Comment by Geksanit** [comment]
Закрывай ишью.
