### ISSUE TITLE
Кастомизация видео

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.2#12]
Где она?)

**Comment by chmnkh** [comment]
На риззоме спрашивали, я так понял, там можно просто айфрейм вставить и всё. 
Ссылки: 
https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_84v6h/
https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_7h477/

**Comment by chmnkh** [comment]
Проглядел бордер радиус, фейл.
Теперь всё.
Там, кстати, в макете видео по высоте совпадать не будет, т.к. соотношение сторон странное и при вставке видео из-за этого полоски черные снизу и сверху появляются, а я сделал 16:9, чтобы все ок было.
