### ISSUE TITLE
Расстояние между слайдерами отличается от макетного

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.2#13]
Из-за этого слово SLIDERS не по центру
![image](https://user-images.githubusercontent.com/26929933/36901052-3e75d138-1e58-11e8-8a54-d64ed4d6f67f.png)

**Comment by Zarwlar** [comment]
Т.е. у тебя в целом весь макет как-то смещён в левую сторону 
![image](https://user-images.githubusercontent.com/26929933/36901128-88e2615a-1e58-11e8-8d39-cc42685f336c.png)

**Comment by chmnkh** [comment]
Слайдеры выровнял, но там не пиксель в пиксель с макетом, ибо в макете правый слайдер стоит чуть левее, чем надо (у меня они флоатами сделаны, поэтому все ок).

**Comment by chmnkh** [comment]
По поводу того, что у меня макет смещен.
В этом макете (как и в первом, в общем-то) все криво: где-то расстояния между элементами разные, где должны бы были быть одинаковые, где-то какие-то элементы смещены на несколько пикселей от центра, хотя они явно должны быть отцентрованы. Насколько я понял из риззомы и из вопросов Сергею, такие штуки можно как раз самому фиксить и забить на то, чтобы с макетом пиксель в пиксель совпадало. Все фейлы макета по этой части расписывать долго, но вообще я могу по каждому месту, где не сходится, пояснить, почему, и где там косяк :)
