### ISSUE TITLE
Нарушен БЭМ

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.2#3]
```
      &-title
        line-height: 1.6em

      &-calendar
        margin: 0

        th
          height: 27px
          padding: 0
          font-family: "Lato", "Arial", sans-serif
          font-size: 9px
          letter-spacing: 0.05em
          color: $white
          background-color: $main-red

        td
          border-right: 1px solid $white
          border-bottom: 1px solid $white
          width: 39px
          padding: 0
```

**Comment by Zarwlar** [comment]
А это что, хаки какие-то?)

```
.select2-container
  width: 100% !important
  .selection
    .select2-selection
      box-sizing: border-box
      outline: none
      border: none
      height: 28px
```
Ещё название класса плохое, тяжело понять, что оно значит

**Comment by chmnkh** [comment]
Там для календаря и дропдауна jquery плагины юзаются, и дефолтные стили так написаны, что чтобы их переопределить/доопределить, приходится вот так вот писать: селекторы тегов юзать (у каких-то элементов тупо классов нету), дикую вложенность делать (ибо дефолтные стили тоже с вложенностью написаны) и так далее. Например в примере с хаками !important вообще ширину в инлайн-стиле переопределяет.
Все то, что ты кинул - это как раз переопределение/доопределение дефолтных стилей плагинов.

**Comment by chmnkh** [comment]
В слайдере, например, тоже что-то подобное, хотя чуть менее жутко, по-моему.

**Comment by chmnkh** [comment]
Dropdown переделал.
По поводу тегов в календаре: в ходе разговора с Иваном, выяснилось, что он делал так же, и это норм.
