### ISSUE TITLE
Pie-Chart

### ISSUE THREAD

**Issue by Zarwlar** [AlexeyCheremnykh/task-2.2#5]
`data-val1=val1 data-val2=val2 data-val3=val3 data-val4=val4`

А что, если будет 10 значений?)

**Comment by AlexeyCheremnykh** [comment]
А на уровне js нужно как-то предусматривать случаи, если > 4 значений будет (т.е. там придется как-то новые цвета генерировать, если > 4 значений, например)? Если нет и фейл именно в тупом ручном перечислении дата-аттрибутов, то исправил.

**Comment by chmnkh** [comment]
Исправил
